# aws_config.py
AWS_ACCESS_KEY = 'YOUR_ACCESS_KEY'
AWS_SECRET_KEY = 'YOUR_SECRET_KEY'
AWS_REGION = 'YOUR_REGION'  
DYNAMODB_TABLE = 'YOUR_TABLE_NAME'
S3_BUCKET = 'YOUR_BUCKET_NAME'
S3_LOCATION = f'https://{S3_BUCKET}.s3.amazonaws.com/'
